### ISSUE TITLE
soc vs. c_tot

### ISSUE THREAD

**Issue by wwieder** [lter/lterwg-som#12]
How are these two variables in our homog data similar / different?

**Comment by piersond** [comment]
Unsure.  Looking at the tarball, I can say there are only a handful of sites with "c_tot" data.  Of those, two have both "soc" and "c_tot" data (SSCZO and an unidentified NEON site)

**Comment by bsulman** [comment]
In the ISCN database, soc referred to soils that had been acid fumigated to remove inorganic C and c_tot was total carbon that was not corrected for inorganic C.

**Comment by srweintraub** [comment]
NEON is same - soc either means the soils were acid-treated prior to analysis, or that the site doesn't have carbonate so we're confident all the C is organic.

**Comment by srearl** [comment]
yeah, let's continue working on key_v2 to be sure we capture this and all the requests

**Comment by piersond** [comment]
@piersond check data for soc vs. ctot vs. pH
