### ISSUE TITLE
web site

### ISSUE THREAD

**Issue by wwieder** [lter/lterwg-som#27]
add authorship and projects tab to website (abstract for 'proposed' papers)

**Comment by srearl** [comment]
also add products tab

**Comment by wwieder** [comment]
@brunj7 when I try building the new site in R I get the error below.  I'm able to knit the site, but links in the header are different among pages?  suggestions?

Error in library(kableExtra) : there is no package called 'kableExtra'
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> library
Execution halted

Exited with status 1.

**Comment by srearl** [comment]
@wwieder the QC plots page requires the `kableExtra` package, so if you are rebuilding the entire website, this package will need to be installed from wherever the code is being run.

**Comment by srearl** [comment]
Will will add kableExtra package in build env to fix this
