### ISSUE TITLE
Create lookup table to constrain keykey user inputs 

### ISSUE THREAD

**Issue by piersond** [lter/lterwg-som#41]

**Comment by wwieder** [comment]
Down the road this could also include the definitions and authorities to make a data catalog for the key-key file

**Comment by srearl** [comment]
is this the same as #51 ? @wwieder @piersond

**Comment by srearl** [comment]
ready to test on [use-key-v2](https://github.com/srearl/soilHarmonization/tree/use-key-v2) branch
