### ISSUE TITLE
modified at timestamp to key file?

### ISSUE THREAD

**Issue by srearl** [lter/lterwg-som#48]
considering ways in which we might keep track of if and when a key file was modified, and use that as a factor as to whether a data package should be homogenized

**Comment by srearl** [comment]
we might be able to get this from the Google Drive statistics, but I am not sure now what we would do with that information? @wwieder @piersond

**Comment by srearl** [comment]
log noting when key files are updated to version 2 will be written. is that sufficient?

**Comment by wwieder** [comment]
I think it's fine.  do we also need to keep track of when a v2 log is updated and OK'd for homog?
