### ISSUE TITLE
NEON Roots & productivity

### ISSUE THREAD

**Issue by wwieder** [lter/lterwg-som#53]
@srweintraub , maybe you already knew this, but I'm a little slow.  It looks like there's another step needed to match variables from multiple sheets / measurement across root and litterfall data from NEON.  There's an example of this in your code that generates the 'master_database' here. https://github.com/lter/lterwg-som/blob/3a74bc4ce2de43d392bce4c67e41359bfc07d0b2/data-processing/getAndWrangleNEONSoilData.R#L210

seems like ANPP and root biomass estimates may be pretty useful- and are thus far sparse in the database.  Would you be willing to help out with this one?

**Comment by srweintraub** [comment]
@wwieder yup you are correct, I haven't yet wrangled the root or litterfall data as I did for soil. I'm happy to help, but probably can't get to this for a week or two. there's enough documentation that someone else could do it if they have time and interest, otherwise I'll tackle closer to Dec.

**Comment by wwieder** [comment]
This is largely done!  Thanks Sam.
Litterfall has also been provided a key-keyV2, but some aspects of the homog are less that ideal. 
The litterfall dataset will take some additional calculations, I'll start a new issue on this.
