### ISSUE TITLE
Update givenUnits in keyV2 to match unit conversion in soilHarmonization

### ISSUE THREAD

**Issue by piersond** [lter/lterwg-som#65]
There are currently many mismatches. Does not appear to be a homogenization issue, simply an issue for providing the correct information to users across all tables/platforms. 

Use unitsConversions %>% print(n = Inf) with the pkg loaded to see the units conversions that the soilHarmonization pkg is using. 

Also need to update the units in the key table we're using for the Shiny app.

**Comment by srearl** [comment]
Derek - can you point out some examples for me?

**Comment by piersond** [comment]
@srearl I can handle this, just wanted to keep you informed. The issue is to fix the unit discrepancies between the soilHarmonization end units, the keyV2_template and the Shiny app data info table. There are currently a handful of differences in units between the three. 

I'll be using the soilHarmonization unit table as the master, from which to check/correct the units in the other two tables. Is that the correct way to go?

**Comment by piersond** [comment]
Fixed. However, best to continue keeping a close eye on units across project components.
