### ISSUE TITLE
get_latest_som broken?

### ISSUE THREAD

**Issue by wwieder** [lter/lterwg-som#76]
I'm not going to spend a ton of time on this, but it seems like this function may be broken (error message below).
Easy enough for me to just pull down the latest tarball, but how should others access it?  I'm guessing it would be through EDI once the database is published?

`Error in add_id_path(nodes, root_id = root_id, leaf = leaf) : 
!anyDuplicated(nodes$id) is not TRUE`

**Comment by srearl** [comment]
That is the darn Google API. Make sure you have the latest release of GoogleDrive. It is working for me but I am afraid this will be case-by-case and depend on folks' Google account details.
