### ISSUE TITLE
rename master to main

### ISSUE THREAD

**Issue by wwieder** [lter/lterwg-som#77]
Trying to  rename master to main with the steps below, but  unable to remove `master`  branch
I also don't want to mess with workflow from others...
@srearl can you advise?

git branch  -m master main
git push  -u origin main
git branch -d origin/master
git branch -u main  origin/main
git branch -u origin/main main

**Comment by wwieder** [comment]
here's how to update local clones  (from https://www.git-tower.com/learn/git/faq/delete-remote-branch)

git checkout master
git branch -m master main
git fetch
git branch --unset-upstream
git branch -u origin/main
git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main

**Comment by srearl** [comment]
@wwieder - Looks like you did it successfully, and I am seeing `main` as one step ahead of `master`. At this point, should just need to delete `master` from GitHub but let us double-check with @brunj7 just to be sure.

**Comment by wwieder** [comment]
I get the following  error  when  I try  to do this

git branch -d origin/master
error: branch 'origin/master' not found.

**Comment by wwieder** [comment]
simililarly 
git push origin --delete origin/master
error: unable to delete 'origin/master': remote ref does not exist
error: failed to push some refs to 'https://github.com/lter/lterwg-som.git'

**Comment by wwieder** [comment]
ahhh!  
git push origin --delete master

**Comment by wwieder** [comment]
@steven I'm going to leave this issue open since there are ways for others  to update their clones here too

**Comment by srearl** [comment]
looks good
